version: '3'

services:
 consolehost:
  image: testhost
  ports:
   - "8000:8000"
  networks:
   - mynat

 consoleclient:
  image: testclient
  networks:
   - mynat
  depends_on:
   - consolehost

networks:
 mynat:
  driver: nat 