version: '3'

services:
 iishost:
  image: 123415425389214897389457981729/wcf-project:iis-host
  ports:
   - "80:80"
  networks:
   - mynat
   
 webapi:
  environment:
   - USERNAME=Container-Viktor
  image: 123415425389214897389457981729/wcf-project:web-api
  ports:
   - "8001:80"
  networks:
   - mynat
  depends_on:
   - iishost  

networks:
 mynat:
  driver: nat 
  
# just compose this file and an IIS host & WebApi will be created on your PC