version: '3'

services:
 consolehost:
  image: host
  ports:
   - "8000:8000"
  networks:
   - mynat

 winformsclient:
  image: client
  networks:
   - mynat
  depends_on:
   - consolehost

networks:
 mynat:
  driver: nat 