//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.StringService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringService.IStringService")]
    public interface IStringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/GetYourString", ReplyAction="http://tempuri.org/IStringService/GetYourStringResponse")]
        string GetYourString(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/GetYourString", ReplyAction="http://tempuri.org/IStringService/GetYourStringResponse")]
        System.Threading.Tasks.Task<string> GetYourStringAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringServiceChannel : ConsoleClient.StringService.IStringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringServiceClient : System.ServiceModel.ClientBase<ConsoleClient.StringService.IStringService>, ConsoleClient.StringService.IStringService {
        
        public StringServiceClient() {
        }
        
        public StringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetYourString(string str) {
            return base.Channel.GetYourString(str);
        }
        
        public System.Threading.Tasks.Task<string> GetYourStringAsync(string str) {
            return base.Channel.GetYourStringAsync(str);
        }
    }
}
